WARNING:root:Requests made without an app_token will be subject to strict throttling limits.
WARNING:root:Requests made without an app_token will be subject to strict throttling limits.
Accessing data APIs
Traceback (most recent call last):
  File "/home/jgodwin/python/covid/covid_plotter.py", line 80, in <module>
    hhs_results = hhs_client.get('g62h-syeh',limit=50000)
  File "/usr/local/lib/python3.6/dist-packages/sodapy/socrata.py", line 413, in get
    "get", resource, headers=headers, params=params
  File "/usr/local/lib/python3.6/dist-packages/sodapy/socrata.py", line 565, in _perform_request
    return response.json()
  File "/usr/local/lib/python3.6/dist-packages/requests/models.py", line 900, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.6/json/decoder.py", line 355, in raw_decode
    obj, end = self.scan_once(s, idx)
MemoryError
